name: Run k6 tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install k6
      run: |
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run k6 tests
      run: |
        k6 run test.js
